local_edition(3)
data(d.represent)
Kro.sp <- minimize(d.represent, outcome = "WNP", include = "?", details = TRUE, show.cases = TRUE)
Kro.tt <- truthTable(d.represent, outcome = WNP)
Kro.sc <- minimize(Kro.tt)
data(d.jobsecurity)
Emm.si <- minimize(d.jobsecurity, outcome = "JSR", incl.cut = 0.9, include = "?", dir.exp = "1,1,1,1,1,0", details = TRUE)
EC1 <- Emm.si$i.sol$C1P1$EC
EC2 <- Emm.si$i.sol$C1P2$EC
data(d.partybans)
HK.sp <- minimize(d.partybans, outcome = "PB[1]", conditions = "C, F, T, V", incl.cut0 = 0.4, include = "?, C", details = TRUE)
HK.si <- minimize(d.partybans, outcome = "PB[1]", conditions = "C, F, T, V", include = "?", dir.exp = "1, 1;2, 2, 1", details = TRUE)
data(d.transport)
SA.si <- minimize(d.transport, outcome = "ACC[1]", conditions = names(d.transport)[1:5], include = "?", dir.exp = "0,1,0,1,1", details = TRUE)
data(d.graduate)
d.Bau <- data.frame(U = c(1,1,1,1,0,0,0,0), D = c(1,1,0,0,1,1,0,0), L = c(1,1,1,1,1,1,0,0), G = c(1,0,1,0,1,0,1,0), E = c(1,1,1,1,1,1,1,0), row.names = letters[1:8])
Bau.cna <- minimize(d.Bau, outcome = names(d.Bau), relation = "sufnec", include = "?", all.sol = FALSE)
d.mmv <- data.frame(A = c(2,0,0,1,1,1,2,2), B = c(2,2,2,2,1,1,0,0), C = c(0,1,0,0,0,2,1,0), D = c(2,1,2,2,3,1,3,0), E = c(3,2,3,3,0,1,3,2), row.names = letters[1:8])
mmv.s <- minimize(d.mmv, outcome = "D[2], E[3]", relation = "sufnec")
mmv.e3 <- minimize(d.mmv, outcome = "~E[3]", include = "?")
data(LC)
ttLC <- truthTable(LC, SURV, sort.by = "incl, n")
cLC <- minimize(ttLC)
ttLCn <- truthTable(LC, ~SURV, sort.by = "incl, n")
pLC <- minimize(ttLC, include = "?", details = TRUE, show.cases = TRUE)
data(LM)
ttLM <- truthTable(LM, SURV, conditions = c(DEV, URB, LIT, IND), sort.by = "incl", show.cases = TRUE)
ttLMn <- truthTable(LM, ~SURV, conditions = c(DEV, URB, LIT, IND), sort.by = "incl", show.cases = TRUE)
ttLM2 <- truthTable(LM, SURV, n.cut = 2, sort.by = "incl", show.cases = TRUE)
data(LF)
ttLF <- truthTable(LF, SURV, incl.cut = 0.7, show.cases = TRUE, sort.by = "incl")
data(CVF)
ttCVF <- truthTable(CVF, outcome = PROTEST, incl.cut = 0.8, show.cases = TRUE, sort.by = "incl, n")
pCVF <- minimize(ttCVF, include = "?", details = TRUE, show.cases = TRUE)
data(RS)


test_that("tests for minimize() have the same output", {
  expect_snapshot(minimize(d.represent, outcome = "WNP"))
  expect_snapshot(minimize(d.represent, outcome = "~WNP"))
  expect_snapshot(Kro.sp)
  expect_snapshot(Kro.sp$PIchart)
  expect_snapshot(Kro.sp$SA)
  expect_snapshot(print(minimize(cbind(Kro.sp$SA[[1]], FO = 1), outcome = "FO")))
  expect_snapshot(print(minimize(cbind(Kro.sp$SA[[2]], FO = 1), outcome = "FO")))
  expect_snapshot(Kro.sc)
  expect_snapshot(minimize(d.jobsecurity, outcome = "JSR", incl.cut    = 0.9, include = "?", details = TRUE))
  expect_snapshot(Emm.si)
  expect_snapshot(pof(Emm.si$i.sol$C1P1$pims, 1 - d.jobsecurity$JSR, relation = "suf"))
  expect_snapshot(Emm.si$i.sol$C1P1$PIchart)
  expect_identical(rownames(Emm.si$SA$S1), rownames(Emm.si$SA$S2))
  expect_snapshot(EC1)
  expect_snapshot(EC2)
  expect_identical(rownames(EC1), rownames(EC2))
  expect_snapshot(minimize(cbind(Emm.si$i.sol$C1P1$EC, FO = 1), outcome = "FO"))
  expect_snapshot(Emm.si$i.sol$C1P1$pims)
  expect_snapshot(minimize(d.jobsecurity, outcome = "~JSR", incl.cut1 = 0.9, incl.cut0 = 0.4, explain="C", include = "?", details = TRUE))
  expect_snapshot(HK.sp)
  expect_snapshot(HK.sp$pims)
  expect_snapshot(rownames(d.partybans[d.partybans$T == 2 & d.partybans$PB != 1, ]))
  expect_snapshot(minimize(d.partybans, outcome = "PB[1]", conditions = "C, F, T, V", incl.cut0 = 0.4, explain = "C"))
  expect_snapshot(HK.si)
  expect_snapshot(SA.si)
  # expect_snapshot(SA.si$i.sol$C1P1$NSEC)
  expect_snapshot(minimize(d.graduate, outcome = "REC", details = TRUE, show.cases = TRUE))
  expect_snapshot(Bau.cna)
  expect_snapshot(print(Bau.cna$E, details = TRUE, show.cases = TRUE))
  expect_snapshot(head(d.mmv))
  expect_snapshot(mmv.s)
  expect_snapshot(print(mmv.s$"E[3]", details = TRUE, show.cases = TRUE))
  expect_snapshot(mmv.e3)
  expect_snapshot(ttLC)
  expect_snapshot(cLC)
  expect_snapshot(minimize(ttLC, details = TRUE, show.cases = TRUE))
  expect_snapshot(minimize(ttLCn))
  expect_snapshot(minimize(ttLCn, include = "?", details = TRUE, show.cases = TRUE))
  expect_snapshot(pLC)
  expect_snapshot(pLC$SA)
  expect_snapshot(minimize(ttLM, details = TRUE, show.cases = TRUE))
  expect_snapshot(minimize(ttLM, include = "?", details = TRUE, show.cases = TRUE))
  expect_snapshot(minimize(ttLMn, details = TRUE, show.cases = TRUE))
  expect_snapshot(minimize(ttLMn, include = "?", details = TRUE, show.cases = TRUE))
  expect_snapshot(minimize(ttLF, details = TRUE, show.cases = TRUE))
  expect_snapshot(minimize(ttLF, include = "?", details = TRUE, show.cases = TRUE))
  expect_snapshot(minimize(ttLF, include = "?", details = TRUE, show.cases = TRUE, dir.exp = "1,1,1,1,1"))
  expect_snapshot(pCVF)
  expect_snapshot(pCVF$PIchart)
  expect_snapshot(minimize(ttCVF, include = "?", row.dom = TRUE, details = TRUE, show.cases = TRUE))
  expect_snapshot(minimize(ttCVF, include = "?", use.letters = TRUE))
  expect_snapshot(minimize(RS, outcome = "REC", details = TRUE, show.cases = TRUE))
  expect_snapshot(minimize(ttLM2, details = TRUE, include = "?"))
})
