local_edition(3)
data(d.represent)
Kro.tt <- truthTable(d.represent, outcome = WNP, n.cut = 2, show.cases = TRUE)
data(d.jobsecurity)
data(d.partybans)
HK.tt <- truthTable(d.partybans, outcome = PB, conditions = c(C, F, T, V), incl.cut = c(1, 0.4))
data(d.graduate)
data(LC)
ttLC <- truthTable(LC, SURV)
data(LM)
ttLM <- truthTable(LM, SURV, n.cut = 2, sort.by = "incl")
data(CVF)
data(RS)
LC3 <- LC
library(declared)
LC3$DEV <- as.factor(LC$DEV)

test_that("tests for truthTable() have the same output", {
  expect_snapshot(truthTable(d.represent, outcome = WNP))
  expect_snapshot(truthTable(d.represent, outcome = WNP, complete = TRUE, show.cases = TRUE, sort.by = "incl = TRUE, n = FALSE"))
  expect_snapshot(truthTable(d.represent, outcome = WNP, complete = TRUE, show.cases = TRUE, sort.by = "incl, n", decreasing = "TRUE, FALSE"))
  expect_snapshot(Kro.tt)
  expect_snapshot(Kro.tt$removed)
  expect_snapshot(truthTable(d.jobsecurity, outcome = JSR, incl.cut = c(0.9, 0.5)))
  expect_snapshot(truthTable(d.jobsecurity, outcome = ~JSR, incl.cut = c(0.9, 0.5)))
  expect_snapshot(HK.tt)
  expect_snapshot(HK.tt$noflevels)
  expect_snapshot(HK.tt$tt[which(HK.tt$tt$n > 2), ])
  expect_snapshot(truthTable(d.partybans, outcome = PB, conditions = c(C, F, T), incl.cut = c(0.9, 0.4), show.cases = TRUE, inf.test = "binom, 0.1"))
  expect_snapshot(truthTable(d.graduate, outcome = REC))
  expect_snapshot(ttLC)
  expect_snapshot(print(ttLC, show.cases = TRUE))
  expect_snapshot(print(ttLC, show.cases = TRUE, complete = TRUE))
  expect_snapshot(truthTable(LC, SURV, complete = TRUE))
  expect_snapshot(truthTable(LC, SURV, complete = TRUE, sort.by = "incl, n"))
  expect_snapshot(truthTable(LC, SURV, complete = TRUE, sort.by = "incl, n = FALSE"))
  expect_snapshot(truthTable(LM, SURV, sort.by = "incl"))
  expect_snapshot(ttLM)
  expect_snapshot(ttLM$removed)
  expect_snapshot(truthTable(CVF, PROTEST, incl.cut = 0.8, sort.by = "incl"))
  expect_snapshot(truthTable(CVF, ~PROTEST, incl.cut = 0.8, sort.by = "incl"))
  expect_snapshot(truthTable(CVF, PROTEST, incl.cut = c(0.8, 0.75), sort.by = "incl"))
  expect_snapshot(truthTable(RS, REC))
  expect_snapshot(truthTable(LC, SURV, incl.cut = 0.8, use.labels = TRUE))
  expect_snapshot(truthTable(LC3, SURV, incl.cut = 0.8, use.labels = TRUE))
})
