local_edition(3)
data(d.represent)
Kro.ss <- superSubset(d.represent, outcome = WNP, incl.cut = 0.9, cov.cut = 0.65)
Kro.coms <- Kro.ss$coms
data(d.partybans)
HK.ss <- superSubset(d.partybans, outcome = PB, conditions = "C, F, T, V")
data(d.jobsecurity)
data(LC)
ssLC <- superSubset(LC, SURV)
data(LM)
data(CVF)
ssCVF <- superSubset(CVF, outcome = PROTEST, incl.cut = 0.90, cov.cut = 0.6)
ssLC4 <- superSubset(LC, outcome = SURV, use.labels = TRUE)

test_that("tests for superSubset() have the same output", {
  expect_snapshot(Kro.ss)
  expect_snapshot(head(Kro.coms))
  expect_snapshot(HK.ss)
  expect_snapshot(HK.ss$coms[1:10, , drop = FALSE])
  expect_snapshot(superSubset(d.jobsecurity, outcome = JSR, relation = "suf", incl.cut = 0.9, cov.cut = 0.4))
  expect_snapshot(superSubset(d.jobsecurity, outcome = ~JSR, relation = "suf", incl.cut = 0.9, cov.cut = 0.4))
  expect_snapshot(ssLC)
  expect_snapshot(superSubset(LM, SURV))
  expect_snapshot(ssCVF)
  expect_snapshot(ssCVF$coms$GEOCON)
  expect_snapshot(superSubset(CVF, outcome = ~PROTEST, incl.cut = 0.90, cov.cut = 0.6))
  expect_snapshot(ssLC4)
})
