local_edition(3)
data(d.represent)
x <- d.represent[, 1:5]
WNP <- d.represent$WNP
data(d.jobsecurity)
Emm.nr <- superSubset(d.jobsecurity, outcome = "JSR", incl.cut = 0.965, cov.cut = 0.6)
Emm.sc <- minimize(d.jobsecurity, outcome = "JSR", incl.cut = 0.9, details = TRUE)
dd <- data.frame(A = c(1,1,1,0,1), B = c(1,1,1,0,1), C = c(0,1,0,0,1), D = c(0,0,1,0,1), O = c(1,1,1,0,1))
data(d.urban)
data(CVF)
conds <- CVF[, 1:5]
PROTEST <- CVF$PROTEST
nCVF <- superSubset(CVF, outcome = PROTEST, incl.cut = 0.90, cov.cut = 0.6)
cCVF <- minimize(CVF, outcome = PROTEST, incl.cut = 0.8, details = TRUE)
inclH <- function(x, y) sum(fuzzyand(x, y)) / sum(fuzzyand(x, y) + sqrt(fuzzyor(x - y, 0)*x))
testdata <- data.frame(X = rep(1, 6), Y = rep(1, 6))

test_that("tests for pof() have the same output", {
  expect_snapshot(pof(x, WNP))
  expect_snapshot(pof(1 - x, WNP))
  expect_snapshot(pof(1 - x, WNP, conditions = names(x)))
  expect_snapshot(pof(x, 1 - WNP))
  expect_snapshot(pof(x, ~WNP, d.represent))
  expect_snapshot(pof(1 - x, 1 - WNP))
  expect_snapshot(pof(x, WNP, relation = "suf"))
  expect_snapshot(pof(x, 1 - WNP, relation = "suf"))
  expect_snapshot(pof(x, WNP, inf.test = "binom", relation = "suf"))
  expect_snapshot(pof(x, WNP, inf.test = "binom"))
  expect_snapshot(Emm.nr)
  expect_snapshot(pof(Emm.nr$coms, 1 - d.jobsecurity$JSR))
  expect_snapshot(pof(1 - Emm.sc$pims, d.jobsecurity$JSR, relation = "suf"))
  expect_snapshot(pof(dd[, -5], dd$O))
  expect_snapshot(pof(dd$A, dd$O))
  expect_snapshot(pof(dd[, 1:2], dd$O))
  expect_snapshot(pof("MLC + FRB -> CP", data = d.urban))
  expect_snapshot(pof("SR~V + CLP~V + SCRP + SLRP -> ~JSR", data = d.jobsecurity))
  expect_snapshot(pof(conds, PROTEST))
  expect_snapshot(pof(1 - conds, PROTEST))
  expect_snapshot(pof(conds, 1 - PROTEST))
  expect_snapshot(pof(conds, ~PROTEST, data = CVF))
  expect_snapshot(pof(conds, PROTEST, relation = "suf"))
  expect_snapshot(pof(conds, 1 - PROTEST, relation = "suf"))
  expect_snapshot(pof(nCVF$coms, 1 - PROTEST))
  expect_snapshot(pof(1 - cCVF$pims, PROTEST))
  expect_snapshot(pof("~NATPRIDE + GEOCON -> PROTEST", data = CVF))
  expect_snapshot(pof("~NATPRIDE + GEOCON -> ~PROTEST", data = CVF))
  expect_snapshot(pof("~NATPRIDE + GEOCON <- PROTEST", data = CVF))
  expect_snapshot(pof("~NATPRIDE + GEOCON -> ~PROTEST", data = CVF, add = inclH))
  expect_snapshot(pof("X <- Y", data = testdata))
})
